FROM httpd:latest

# Copy the entire directory to the appropriate location in the container
COPY . /usr/local/apache2/htdocs/

# Expose port 80 to the outside world
EXPOSE 80

# final project for DevOp subject already run it on docker and on public server which is render.com my weblink : https://image-uploader-v1.onrender.com/